name: CI

on:
  push: { branches: [main] }

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v2
        with: { node-version: "16" }
      - run: yarn
      - run: yarn build
      - run: yarn lint
